apps/equipments/urls.py
from django.conf.urls import url
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

from .views import *

app_name = 'equipments'
urlpatterns = [
    path('configurations/equipment/create', EquipmentCreate.as_view(), name='equipment_create'),
    path('configurations/equipment/index', EquipmentList.as_view(), name='equipment_list'),
    path('configurations/equipment/update/<int:pk>/', EquipmentUpdate.as_view(), name='equipment_update'),
    path('configurations/equipment/inspection/items/<int:pk>/', EquipmentInspetionItem.as_view(), name='equipment_inspetion_items'),
    path('configurations/equipment/inspection/items/update/<int:pk>/', EquipmentInspetionItemUpdate.as_view(), name='equipment_inspetion_items_update'),
    path('configurations/equipment/inspection/delete/', EquipmentInspetionItemDelete.as_view(), name='equipment_inspetion_items_delete'),
    path('equipment_delete', EquipmentDelete.as_view(), name='equipment_delete'),
    path('configurations/supplies/index', SupplyList.as_view(), name='supply_list'),
    path('configurations/supplies/create', SupplieCreateView.as_view(), name='supply_create'),
    path('configurations/supplies/edit/<int:pk>/', SupplyUpdate.as_view(), name='supply_edit'),
    path('supplies/delete/', SupplyDelete.as_view(), name='supply_delete'),
    path('configurations/perposition/index', PerPositionList.as_view(), name='perposition_list'),
    path('perposition/create', AsignEquipment.as_view(), name='perposition_create'),
    path('perposition_delete', PerPositionDelete.as_view(), name='perposition_delete'),
    path('perposition_save', PerPositionSave.as_view(), name='perposition_save'),
    path('perposition/update/<int:pk>/', PerpositionUpdate.as_view(), name='perposition_update'),
    path('asign_equipment_list', AsingEquipmentList.as_view(), name='asign_equipment_list'),
    path('<int:equipment>/documents/create/', EquipmentDocCreate.as_view(), name='equipment_doc_create'),
    path('<int:pk>/documents/show/', EquipmentDocShow.as_view(), name='equipment_doc_show'),
    path('documents/update/<int:pk>', EquipmentDocEdit.as_view(), name='equipment_doc_update'),
    path('documents/delete/', EquipmentDocDelete.as_view(), name='equipment_doc_delete'),
    path('<int:equipment>/image/create/', EquipmentImgCreate.as_view(), name='equipment_img_create'),
    path('<int:pk>/image/index/', EquipmentImgIndex.as_view(), name='equipment_img_index'),
    path('image/update/<int:pk>', EquipmentImgEdit.as_view(), name='equipment_img_update'),
    path('image/delete/', EquipmentImgDelete.as_view(), name='equipment_img_delete'),
    path('get', EquipmentGetJx.as_view(), name='equipment_getjx'),
    path('supply/get', SupplyGetJx.as_view(), name='supply_getjx'),
    path('<int:pk>/video/show/', EquipmentVideoShow.as_view(), name='equipment_video_show'),
    path('video/update/<int:pk>', EquipmentVideoEdit.as_view(), name='equipment_video_update'),
    path('<int:equipment>/video/create/', EquipmentVideoCreate.as_view(), name='equipment_video_create'),
    path('video/delete/', EquipmentVideoDelete.as_view(), name='equipment_video_delete'),
]

ippe/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
import notifications.urls
from django.contrib.staticfiles import views
from django.urls import re_path
from django.views.i18n import JavaScriptCatalog
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.base.urls', namespace='base')),
    path('login/', include('apps.authenticate.urls')),
    path('elements/', include('apps.elements.urls', namespace='elements')),
    path('sizes/', include('apps.sizes.urls', namespace='sizes')),
    path('requests/', include('apps.requests.urls', namespace='requests')),
    path('equipments/', include('apps.equipments.urls', namespace='equipments')),
    path('warehouses/', include('apps.warehouses.urls', namespace='warehouses')),
    #path('providers/', include('apps.inventories.urls', namespace='inventories')),
    path('employees/', include('apps.employees.urls', namespace='employees')),
    path('inventories/', include('apps.inventories.urls', namespace='inventories')),
    path('assignments/', include('apps.assignments.urls', namespace='assignments')),
    path('reports/', include('apps.reports.urls', namespace='reports')),
    path('publications/', include('apps.publications.urls', namespace='publications')),
    path('summernote/', include('django_summernote.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),

    path('api/v1/', include('apps.api.urls')),

    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('i18n/', include('django.conf.urls.i18n')),
]


if settings.DEBUG:
    
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', views.serve),
    ]
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/equipments/models.py
from django.db import models
from apps.elements.models import Classification
from apps.sizes.models import Area,Size
import os
from django_serializable_model import SerializableModel
# Create your models here.

class Equipment(models.Model):
    DIARY = -1
    FOR_DAMAGE = 0
    EVERY_ONE_MONSTH = 1 
    EVERY_TWO_MONSTH = 2
    EVERY_TREE_MONSTH = 3
    EVERY_FOUR_MONSTH = 4
    EVERY_SIX_MONSTH = 6
    EVERY_ONE_YEAR = 12
    EVERY_TWO_YEAR = 24

    FREQUENCY_OF_CHANGE_CHOICES = [
        (DIARY,'Daily(1 day)' ),
        (FOR_DAMAGE,'Only For Damage'),
        (EVERY_ONE_MONSTH,'Monthly (30 days)'),
        (EVERY_TWO_MONSTH,'Every TWO (02) months'),
        (EVERY_TREE_MONSTH,'Every TREE (03)months'),
        (EVERY_FOUR_MONSTH,'Every FOUR (04)months'),
        (EVERY_SIX_MONSTH,'Every SIX (06) months'),
        (EVERY_ONE_YEAR,'Annually (12 months)'),
        (EVERY_TWO_YEAR,'Every 02 Years (02 years)'),
        ]

    code = models.CharField(unique=True, max_length = 10 , null=True)
    name = models.CharField(max_length=80, null=True)
    element_classification = models.ForeignKey(Classification,null=True,blank=True, on_delete=models.SET_NULL)
    area = models.ForeignKey(Area , null=True,blank=True, on_delete=models.SET_NULL)    
    time_of_life = models.IntegerField( blank=True, null=True)
    description = models.TextField( null=True, blank=True)
    mantenace_cleaning = models.TextField(null=True)
    certification = models.CharField(max_length=30, null=True)
    mode_use = models.TextField( null=True, blank=True)
    status = models.BooleanField(null=True , blank=True)
    required_inspection = models.BooleanField( default=True)
    #check_mode_uso = models.BooleanField( default=False)
    #check_mantenace_cleaning = models.BooleanField( default=False)
    #check_condition = models.BooleanField( default=False)
    frequency_of_change =  models.IntegerField(choices=FREQUENCY_OF_CHANGE_CHOICES, default=FOR_DAMAGE)
    is_disposable = models.BooleanField( default=False)
    position = models.ManyToManyField(to='organizational.Position', through='PerPosition', related_name='Equipment_position')
    company  = models.ForeignKey(to='organizational.Company',  null=True, blank=True, on_delete=models.SET_NULL)
    image = models.ImageField(upload_to='uploads/equipments/profile/',null=True, blank=True, verbose_name='image_')
    create_date = models.DateTimeField(auto_now_add=True, blank=True,  null=True)    
    modified_date = models.DateTimeField( auto_now=True, blank=True,  null=True)

    
      

    def __str__(self):
        return '(%s-%s-%s) %s' % (self.element_classification.element_type.code,self.element_classification.code, self.code,self.name )

    def get_element_type_name(self):
         return '(%s) %s' % (self.element_classification.element_type.code, self.element_classification.element_type.name )  

    def get_element_type_description(self):
         return '%s' % (self.element_classification.element_type.description )     

    def get_element_class_description(self):
         return '%s' % (  self.element_classification.description )      

    def get_element_class_name(self):
         return '(%s) %s' % (self.element_classification.code, self.element_classification.name )  

    def get_documents(self):
        return self.document_set.all().order_by('-modified_date')  

    def get_firts_documents(self):
        return self.document_set.all()

    def get_prim_doc(self):
        return self.document_set.all().order_by('-modified_date').first() 

    def get_items_inspection(self):
        return self.itemsinspection_set.all().order_by('-modified_date')  

    def get_items_inspection_count(self):
        return self.itemsinspection_set.all().count()
    
    def frequency_of_change_text(self):      
        for choice in self.FREQUENCY_OF_CHANGE_CHOICES:
            if choice[0] == self.frequency_of_change:
                return choice[1]
        return self.FREQUENCY_OF_CHANGE_CHOICES[1][1] 
        #return self.FREQUENCY_OF_CHANGE_CHOICES[self.frequency_of_change]    
class Brand(models.Model):
    code = models.CharField(unique=True,max_length = 10 , null=True)
    name = models.CharField(max_length=30, null=True)
    create_date = models.DateTimeField(auto_now_add=True)    
    modified_date = models.DateTimeField( auto_now=True)

    def __str__(self):
        return '%s' % (self.name)
    

class Supply(models.Model):
    GENDER_MALE = 0
    GENDER_FEMALE = 1
    GENDER_UNISEX = 2
    GENDER_CHOICES = [(GENDER_MALE, 'Male'), (GENDER_FEMALE, 'Female'), (GENDER_UNISEX,'Unisex')]
    code = models.CharField(unique=True,max_length = 15 , null=True)
    equipment = models.ForeignKey(Equipment , null=True,blank=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=30, null=True)
    description = models.TextField( null=True, blank=True)
    size = models.ForeignKey(Size,null=True,blank=True, on_delete=models.SET_NULL)
    color = models.ForeignKey(to='equipments.color',null=True,blank=True, on_delete=models.SET_NULL)
    brand = models.ForeignKey(Brand ,null=True,blank=True, on_delete=models.SET_NULL)
    material = models.TextField(max_length=30, null=True)
    gender = models.IntegerField(choices=GENDER_CHOICES, default=GENDER_UNISEX)
    unid_content = models.IntegerField( default=1, blank=False, null=False)
    status = models.BooleanField(null=True, blank=True, default=True) 
    company     = models.ForeignKey(to='organizational.Company',  null=True, blank=True, on_delete=models.SET_NULL)
    create_date = models.DateTimeField(auto_now_add=True, blank=True,  null=True)    
    modified_date = models.DateTimeField( auto_now=True, blank=True,  null=True)

           

    def __str__(self):
        return '%s %s %s' % (self.code, self.equipment,self.name)

    def natural_key(self):
        return django_sub_dict(self)    
        
    def gender_text(self):        
        return self.GENDER_CHOICES[self.gender][1]

    def gender_icon_class(self):
        GENDER_ICONS = ["fa fa-male text-blue-darker","fa fa-female text-pink-darker","fa fa-venus-mars .text-green-darker"]    
        return GENDER_ICONS[self.gender]

    def status_text(self):
        return {True: 'Activated',False: 'Deactivated'}[self.status]    

    def get_documents(self):
        return self.document_set.all     
        
    def get_images(self):
        return self.photo_set.all   

    def get_video(self):
        return self.equipment.video_set.all

    def get_photo_url(self):
        return self.equipment.image.url    

    def get_photo(self):
        return self.equipment.image        

    def equipment_name(self):
        return '(%s) %s' % (self.equipment.code, self.equipment.name)    

    def equipment_description(self):       
        return '%s' % (self.equipment.description)      

    def get_photo(self):
        return self.equipment.image   

    def get_post_invetary(self):
        movement = self.movement_set.latest('id')
        if movement:
          return  movement.post_inventory
        return  0   

    def get_post_invetary_for_warehouse(self,warehouse_id):    
        movement = self.movement_set.filter(warehouse_id=warehouse_id)
        if movement:
            movement = movement.latest('id')
            return  movement.post_inventory
        return  0 
    def get_delivered_date(self):
        delivered =  self.delivereddetail_set.all() 
        delivered = delivered.latest('id')
        return delivered.modified_date 

class Color(models.Model):
    name = models.CharField(unique=True,max_length=20, null=True)
    create_date = models.DateTimeField(auto_now_add=True, blank=True,  null=True)    
    modified_date = models.DateTimeField( auto_now=True, blank=True,  null=True)
    def __str__(self):
        return '%s' % (self.name)

  

class PerPosition(models.Model):
    position = models.ForeignKey(to='organizational.Position' , null=True,blank=True, on_delete=models.CASCADE, related_name='position_equipment')
    equipment = models.ForeignKey(Equipment , null=True,blank=True, on_delete=models.CASCADE)
    description = models.TextField( null=True, blank=True)
    maximum = models.IntegerField(null=True)
    start_date = models.DateTimeField(null=True, blank=True)    
    end_date = models.DateTimeField(null=True, blank=True)  
    inspection_period = models.IntegerField(null=True)
    color = models.CharField(max_length=30, null=True)    
    company     = models.ForeignKey(to='organizational.Company',  null=True, blank=True, on_delete=models.SET_NULL)
    create_date = models.DateTimeField(auto_now_add=True, blank=True,  null=True)    
    modified_date = models.DateTimeField( auto_now=True, blank=True,  null=True)

class Photo(models.Model):
    equipment_by = models.ForeignKey(Equipment , null=True,blank=True, on_delete=models.CASCADE)
    photo = models.ImageField(upload_to='uploads/equipments/photos/',null=True, blank=True, verbose_name='photo_')
    title     = models.CharField(max_length=130,null=True)    
    description = models.TextField(max_length=850,null=True)
    create_date = models.DateTimeField(auto_now_add=True, blank=True,  null=True)    
    modified_date = models.DateTimeField( auto_now=True, blank=True,  null=True)

    def extension(self):
        name, extension = os.path.splitext(self.document.name)
        return extension

class Video(models.Model):
    equipment_by = models.ForeignKey(Equipment, null=True,blank=True, on_delete=models.SET_NULL)
    video = models.CharField(max_length=200,null=False, blank=False)
    title     = models.CharField(max_length=150,null=True)
    description = models.TextField(max_length=800,null=True, blank=True)

apps/sizes/models.py
from django.db import models
from apps.employees.models import Employee

from django_serializable_model import SerializableModel

# Create your models here.


class Area(models.Model):
    code = models.CharField(unique=True,max_length=10, null=False)
    name = models.TextField(max_length=20, null=True)
    description = models.TextField(max_length=50, null=True)
    status = models.BooleanField(null=True, blank=True)
    create_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '(%s) %s' % (self.code, self.name)
class Size(SerializableModel):
    GENDER_MALE = 0
    GENDER_FEMALE = 1
    GENDER_UNISEX = 2
    GENDER_CHOICES = [(GENDER_MALE, 'Male'), (GENDER_FEMALE, 'Female'), (GENDER_UNISEX,'Unisex')]
    code = models.CharField( max_length=10,null=False)
    gender = models.IntegerField(choices=GENDER_CHOICES, default=GENDER_UNISEX)
    body_area = models.ForeignKey(Area,  on_delete=models.CASCADE, null=True, blank=True) 
    description = models.TextField(max_length=250, null=True, blank=True)
    status = models.BooleanField(null=True, blank=True, default=True)    
    name = models.TextField(max_length=20, null=True)
    create_date = models.DateTimeField(auto_now_add=True)
    modified_date = models.DateTimeField(auto_now=True)
    class Meta:
        constraints = [
            models.UniqueConstraint(fields= ['code','gender','body_area'],name='size_code_gender_body_area_unique'),
        ]
    

    def gender_text(self):        
        return self.GENDER_CHOICES[self.gender][1]

    def gender_icon_class(self):
        GENDER_ICONS = ["fa fa-male text-blue-darker","fa fa-female text-pink-darker","fa fa-venus-mars .text-green-darker"]    
        return GENDER_ICONS[self.gender]

    def __str__(self):
        return '(%s-%s) %s' % (self.code, self.GENDER_CHOICES[self.gender][1], self.name)

apps/equipments/templates/equipment_list.html
{% extends 'base.html' %}
{% load static %}
 {% load i18n %}
{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="javascript:;">{% blocktrans %}Home{% endblocktrans %}</a></li>
    <li class="breadcrumb-item"><a href="javascript:;">{% blocktrans %}Equipment{% endblocktrans %}</a></li>
    <li class="breadcrumb-item active">{% blocktrans %}Equipment List{% endblocktrans %}</li>
{% endblock breadcrumb %}
{% block page_header_title %}{% blocktrans %}Equipment{% endblocktrans %}{% endblock page_header_title %}
{% block page_header_sm_title %}{% blocktrans %}This is the element equipment list{% endblocktrans %}{% endblock page_header_sm_title %}
{% block content %}
    {% include 'table_base.html' with info=dataTable %} 
{% endblock content%}
{% block custom_css %}
	<link href="{% static 'css/default/table_base_icon_count.css' %}" rel="stylesheet" />
{% endblock custom_css %}
{% block menu_active_configuration %}<li class="has-sub active">{% endblock menu_active_configuration %}
{% block menu_equipment %}
<li class="has-sub active">
	<a ><b class="caret"></b>{% blocktrans %}Equipments{% endblocktrans %}</a>
	<ul class="sub-menu">
		<li class="active"><a href="{% url 'equipments:equipment_list'%}">{% blocktrans %}Equipments{% endblocktrans %}</a></li>
		<li><a href="{% url 'equipments:supply_list'%}">{% blocktrans %}Supplies{% endblocktrans %}</a></li>
		<li><a href="{% url 'equipments:perposition_list'%}">{% blocktrans %}Asig. Position{% endblocktrans %}</a></li>
	</ul> 
</li>
{% endblock menu_equipment %}
{% block custom_js %}
	<link href="{% static 'plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" />
	<link href="{% static 'plugins/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" />
	<link href="{% static 'plugins/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" rel="stylesheet" />

    <script src="{% static 'custom_type.js' %}"></script>
	<!-- ================== BEGIN PAGE LEVEL JS ================== -->
		<!-- ================== BEGIN PAGE LEVEL JS ================== -->
	<script src="{% static 'plugins/datatables.net/js/jquery.dataTables.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>
	
	<script src="{% static 'plugins/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-buttons/js/buttons.print.min.js' %}"></script>

	<script src="{% static 'plugins/pdfmake/build/pdfmake.min.js' %}"></script>
	<script src="{% static 'plugins/pdfmake/build/vfs_fonts.js' %}"></script>
	<script src="{% static 'plugins/jszip/dist/jszip.min.js' %}"></script>
	<script src="{% static 'js/demo/table-manage-buttons.demo.js' %}"></script>
    <script src="{% static 'plugins/highlight.js/highlight.min.js' %}"></script>
    <script src="{% static 'js/demo/render.highlight.js' %}"></script>
	<!-- ================== END PAGE LEVEL JS ================== -->
	<!-- ================== END PAGE LEVEL JS ================== -->
{% endblock custom_js %}

apps/equipments/templates/equipment_video_show.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
 {% load i18n %}
{% block custom_css %}
	<link rel="stylesheet" type="text/css" href="{% static 'plugins/slick-jquery/css/slick.css' %}"/>
	<link rel="stylesheet" type="text/css" href="{% static 'plugins/slick-jquery/css/slick-theme.css' %}"/>
{% endblock custom_css %}
{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="javascript:;">{% blocktrans %}Home{% endblocktrans %}</a></li>
    <li class="breadcrumb-item"><a href="javascript:;">{% blocktrans %}Equipment{% endblocktrans %}</a></li>
    <li class="breadcrumb-item active">{% blocktrans %}Equipment List{% endblocktrans %}</li>
{% endblock breadcrumb %}
{% block page_header_title %}{% blocktrans %}Equipment -  Videos{% endblocktrans %}{% endblock page_header_title %}
{% block page_header_sm_title %}{% blocktrans %}This is Videos equipment list{% endblocktrans %}{% endblock page_header_sm_title %}
{% block menu_active_configuration %}<li class="has-sub active">{% endblock menu_active_configuration %}
{% block menu_equipment %}
<li class="has-sub active">
	<a ><b class="caret"></b>{% blocktrans %}Equipments{% endblocktrans %}</a>
	<ul class="sub-menu">
		<li class="active"><a href="{% url 'equipments:equipment_list'%}">{% blocktrans %}Equipments{% endblocktrans %}</a></li>
		<li><a href="{% url 'equipments:supply_list'%}">{% blocktrans %}Supplies{% endblocktrans %}</a></li>
		<li><a href="{% url 'equipments:perposition_list'%}">{% blocktrans %}Asig. Position{% endblocktrans %}</a></li>
	</ul> 
</li>
{% endblock menu_equipment %}
{% block content %}

<div class="row">
<!-- begin col-6 -->
	<div class="col-xl-12">
		<!-- begin panel -->
		<div class="panel panel-success" data-sortable-id="form-stuff-10">
			<!-- begin panel-heading -->
			<div class="panel-heading">
				<h4 class="panel-title">{% blocktrans %}Gallery - Equipment Videos{% endblocktrans %}</h4>
				
			</div>
			<!-- end panel-heading -->
			<!-- begin panel-body -->
			<div class="panel-body ">      
			    <div class='row'>
					<div>
						<ul class="result-list">
							<li>
								<a href="#" class="result-image width-250 height-250" style="background-image: url({{ equipments.image.url }})"></a>
								<div class="result-info">
									<h1 class=""> <span class="badge badge-info">{{ equipments.code }}</span> {{ equipments.name }}</h2>
									<p class="desc f-s-14">
										{{ equipments.description }}
									</p>
									<div class="btn-row">
										<a href="{% url 'equipments:equipment_list' %}" data-toggle="tooltip" data-container="body" data-title="Table list"><i class="fa fa-fw fa-table"></i></a>
										<a href="{% url 'equipments:equipment_update' equipments.id  %}" data-toggle="tooltip" data-container="body" data-title="Configuration"><i class="fa fa-fw fa-cog"></i></a>
										<a href="{% url 'equipments:equipment_img_index' equipments.id %}" data-toggle="tooltip" data-container="body" data-title="Images"><i class="fas fa-fw fa-image"></i></a>
										<a href="{% url 'equipments:equipment_doc_show' equipments.id %}" data-toggle="tooltip" data-container="body" data-title="Documents"><i class="fas fa-fw fa-file"></i></a>
										<a href="{% url 'equipments:equipment_video_show' equipments.id %}" data-toggle="tooltip" data-container="body" data-title="Links Videos"><i class="fab fa-youtube"></i></a>										
									</div>
								</div>								
							</li>
						</ul>
					</div>
				</div>
			</div>	
			<div class="panel-body "> 
				<div class="row">			
					<div class="col-lg-12 col-lg-offset-2">
						<h4 class="text-center m">{% blocktrans %}Equipment Video gallery{% endblocktrans %}</h4>
						<a href="{% url 'equipments:equipment_video_create' equipments.id %}" 
							class="btn btn-sm  btn-primary  "> 
							<i class="fa fa-plus-circle fa-2x  " aria-hidden="true"></i> {% blocktrans %}Add New{% endblocktrans %}
						</a>
						<div class="slick_image">
							{% for video in equipments.video_set.all   %}
							<!-- begin card -->
							<div class="card border-0">
								<iframe width="380" height="215" 
									src="https://www.youtube.com/embed/{{video.video}}" frameborder="0" 
									allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" 
									allowfullscreen>
								</iframe>
								<div class="card-body">
									<h4 class="card-title m-t-0 m-b-10">{{video.title|title}}</h4>
									<p class="card-text">
										{{video.description}}
									</p>
									<a class="btn btn-sm btn-default"  
										href="{% url 'equipments:equipment_video_update' video.id  %}">
										<i class="fas fa-edit"></i>
									</a>
									<a class="btn btn-sm btn-default" 
										data-toggle="modal" data-target="#delete" data-pk="{{ video.id }}" >
									 	<i class="fa fa-trash" aria-hidden="true"></i>
									</a>
									
								</div>
							</div>
							<!-- end card -->
							{% endfor  %}							
						</div>
					</div>
					<div class="col text-center">
						<a class="btn btn-sm btn-primary m-r-5"
						 href="{%url 'equipments:equipment_list' %}">{% blocktrans %}Back{% endblocktrans %}</a>
					</div>
                </div>
				
	   <!-- DELETE MODAL -->
    <div class="modal fade" id="delete">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">{% blocktrans %}Delete Confirmation{% endblocktrans %}</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
                </div>
                <div class="modal-body ">
                    <div class="alert alert-danger m-b-0">
                        <h5><i class="fa fa-info-circle"></i> {% blocktrans %}Are You Sure?{% endblocktrans %}</h5>
                        <p>{% blocktrans %}Do you really want to delete these records? This process cannot be undone.{% endblocktrans %}</p>
                    </div>
                </div>
                <div class="modal-footer">
                    <form action="{% url 'equipments:equipment_video_delete'  %}" method="POST">
                        {% csrf_token %}  
                        <a class="btn btn-white" data-dismiss="modal">{% blocktrans %}Close{% endblocktrans %}</a>
                        <button type="submit" class="btn btn-danger delete-button" name="delete_id" id="delete-button" value="" >{% blocktrans %}Delete{% endblocktrans %}</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
	 <!-- DELETE MODAL -->			
</div>
			


{% endblock %}



{% block custom_js %}
<script type="text/javascript" src="//code.jquery.com/jquery-migrate-1.2.1.min.js"></script>
<script src="{% static 'custom_type.js' %}"></script>
<script src="{% static 'js/video_show.js' %}"></script>
<script type="text/javascript" src="{% static 'plugins/slick-jquery/js/slick.js' %}"></script>
    
{% endblock %}