apps/assignments/urls.py
from django.conf.urls import url
from django.urls import path,include

from .views import *

app_name = 'assignments'
urlpatterns = [
	path('inspections/list', InspectionList.as_view(), name='inspection_list'),
	path('inspections/select/', InspectionSelect.as_view(), name='inspection_select'),
	path('delivered_ajax', DeliveredAjax.as_view(), name='delivered_ajax'),
	path('inspections/view/<int:pk>', ViewInspection.as_view(), name='inspection_view'),
]

ippe/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
import notifications.urls
from django.contrib.staticfiles import views
from django.urls import re_path
from django.views.i18n import JavaScriptCatalog
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.base.urls', namespace='base')),
    path('login/', include('apps.authenticate.urls')),
    path('elements/', include('apps.elements.urls', namespace='elements')),
    path('sizes/', include('apps.sizes.urls', namespace='sizes')),
    path('requests/', include('apps.requests.urls', namespace='requests')),
    path('equipments/', include('apps.equipments.urls', namespace='equipments')),
    path('warehouses/', include('apps.warehouses.urls', namespace='warehouses')),
    #path('providers/', include('apps.inventories.urls', namespace='inventories')),
    path('employees/', include('apps.employees.urls', namespace='employees')),
    path('inventories/', include('apps.inventories.urls', namespace='inventories')),
    path('assignments/', include('apps.assignments.urls', namespace='assignments')),
    path('reports/', include('apps.reports.urls', namespace='reports')),
    path('publications/', include('apps.publications.urls', namespace='publications')),
    path('summernote/', include('django_summernote.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),

    path('api/v1/', include('apps.api.urls')),

    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('i18n/', include('django.conf.urls.i18n')),
]


if settings.DEBUG:
    
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', views.serve),
    ]
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/assignments/models.py
from django.db import models
from apps.employees.models import Employee
from apps.equipments.models import PerPosition, Supply, Equipment, ItemsInspection
from apps.inventories.models import CheckOutPut, CheckOutPutDetail, Movement
from django.contrib.auth.models import User
# Create your models here.

class Delivered(models.Model):
    CODE_PENDING = 1
    CODE_COMPLETED = 2
    CODE_INCOMPLETED = 3

    STATUS_CHOICES = [
        (CODE_PENDING, 'Pending'),
        (CODE_COMPLETED, 'Completed'),
        (CODE_INCOMPLETED, 'Incompleted'),
    ]
    BADGE_CHOICES = [
        (CODE_PENDING,'badge-warning'),
        (CODE_COMPLETED, 'badge-success'),
        (CODE_INCOMPLETED, 'badge-danger'),
    ]
    employee = models.ForeignKey(to='employees.Employee',related_name='delivered_employee', null=True, blank=True, on_delete=models.SET_NULL)
    deliverer = models.ForeignKey(User, related_name='delivered_deliverer', null=True, blank=True, on_delete=models.SET_NULL)
    observation = models.TextField(max_length=250)
    create_date = models.DateTimeField(auto_now_add=True, blank=True,  null=True)    
    modified_date = models.DateTimeField( auto_now=True, blank=True,  null=True)
    checkout = models.ForeignKey(CheckOutPut, null=True, blank=True, on_delete=models.SET_NULL)
    status = models.IntegerField(choices=STATUS_CHOICES, default=CODE_PENDING)
    def __str__(self):
        return '%s' % ( self.employee)
        
    def details(self):
        return self.delivereddetail_set.all()

    def status_text(self):        
        return self.STATUS_CHOICES[self.status-1][1]    

    def get_level_badge(self):    
        return self.BADGE_CHOICES[self.status-1][1]

class DeliveredDetail(models.Model):
    CODE_PENDING = 1
    CODE_ACCEPTED = 2
    CODE_REFUSED = 3

    STATUS_CHOICES = [
        (CODE_PENDING, 'Pending'),
        (CODE_ACCEPTED, 'Accepted'),
        (CODE_REFUSED, 'Refused'),
    ]

    delivered = models.ForeignKey(Delivered, null=True, blank=True, on_delete=models.SET_NULL)        
    observation = models.TextField(max_length=250)
    is_accept   = models.IntegerField(choices=STATUS_CHOICES, default=CODE_PENDING, null=True, blank=True)
    expire_date = models.DateField( blank=True,  null=True)
    supply      = models.ForeignKey(Supply, null=True, blank=True, on_delete=models.SET_NULL) 
    create_date = models.DateTimeField(auto_now_add=True, blank=True,  null=True)    
    modified_date = models.DateTimeField( auto_now=True, blank=True,  null=True)
    movement = models.ForeignKey(Movement, null=True, blank=True, on_delete=models.SET_NULL)
    checkout_detail = models.ForeignKey(CheckOutPutDetail, null=True, blank=True, on_delete=models.SET_NULL)
#falta campos de movimiento de inventario y salida del almacen
    def __str__(self):
        return '%s %s' % ( self.delivered,self.supply )

    def get_image(self):
        return self.supply.get_photo()

class EmployeeInspection(models.Model):
    BADGE_CHOICES = [
        ('0','badge-danger'),
        ('33','badge-danger'),
        ('66', 'badge-warning'),
        ('99','badge-primary'),
        ]
    employee = models.ForeignKey(Employee, null=True, blank=True, on_delete=models.SET_NULL)
    inspection_date = models.DateField(auto_now_add=True)
    observation = models.TextField(max_length=800,default='N/A')
    qualification = models.DecimalField(max_digits=5, decimal_places=2, null=True, blank=True,default=0)

    def inspectioned_elements_count(self):
        return self.employeeinspectiondetail_set.count()

    def get_class_badge_level_average(self):
            if  self.qualification:
                if self.qualification <= 33:
                    return EmployeeInspection.BADGE_CHOICES[1][1]
                elif self.qualification > 33 and self.qualification < 66:
                    return EmployeeInspection.BADGE_CHOICES[2][1]
                elif self.qualification >= 66:
                    return EmployeeInspection.BADGE_CHOICES[3][1]
            else:
                return EmployeeInspection.BADGE_CHOICES[0][1]    

class EmployeeInspectionDetail(models.Model):
    employee_inspection = models.ForeignKey(EmployeeInspection, null=True, blank=True, on_delete=models.SET_NULL)
    delivered_detail = models.ForeignKey(DeliveredDetail, null=True, blank=True, on_delete=models.SET_NULL)
    supply      = models.ForeignKey(Supply, null=True, blank=True, on_delete=models.SET_NULL) 
    equipment = models.ForeignKey(Equipment, null=True, blank=True, on_delete=models.SET_NULL)   

    average = models.DecimalField(max_digits=5, decimal_places=2, blank=True,  null=True,default=0)
    observation = models.TextField(max_length=800,default='N/A')
    create_date = models.DateTimeField(auto_now_add=True, blank=True,  null=True)    
    modified_date = models.DateTimeField( auto_now=True, blank=True,  null=True)

    def get_class_badge_level_average(self):
            if  self.average:
                if self.average <= 33:
                    return EmployeeInspection.BADGE_CHOICES[1][1]
                elif self.average > 33 and self.average < 66:
                    return EmployeeInspection.BADGE_CHOICES[2][1]
                elif self.average >= 66:
                    return EmployeeInspection.BADGE_CHOICES[3][1]
            else:
                return EmployeeInspection.BADGE_CHOICES[0][1]

class   EmployeeInspectionDetailResponse(models.Model):
    items_inspection = models.ForeignKey(ItemsInspection, null=True, blank=True, on_delete=models.SET_NULL)
    employee_inspection_detail = models.ForeignKey(EmployeeInspectionDetail, null=True, blank=True, on_delete=models.SET_NULL)
    is_positive   = models.BooleanField(default=False)

    create_date = models.DateTimeField(auto_now_add=True, blank=True,  null=True)    
    modified_date = models.DateTimeField( auto_now=True, blank=True,  null=True)

apps/assignments/forms.py
from django import forms

from .models import *
from django.utils.translation import ugettext_lazy as _
class EmployeeInspectionForm(forms.ModelForm):
    class Meta:
        model = EmployeeInspection
        fields = [
            'employee',          
        ]
        labels = {
            'employee' : _('Employee'),
        }
        widgets = {
            'employee' : forms.Select(attrs={'class':'form-control',}), 
        }

apps/assignments/templates/inspection_list.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="javascript:;">{% blocktrans %}Home{% endblocktrans %}</a></li>
    <li class="breadcrumb-item"><a href="javascript:;">{% blocktrans %}Inspection{% endblocktrans %}</a></li>
    <li class="breadcrumb-item active">{% blocktrans %}Make an Inspection{% endblocktrans %}</li>
{% endblock breadcrumb %}
{% block custom_css %}
	<link href="{% static '/css/stars.css' %}" rel="stylesheet" />
{% endblock custom_css %}
{% block page_header_title %}{% blocktrans %}Inspection List{% endblocktrans %}{% endblock page_header_title %}
{% block page_header_sm_title %}{% blocktrans %}Here you can view the inpection list{% endblocktrans %}{% endblock page_header_sm_title %}
{% block menu_active_inspections %}<li class="has-sub active">{% endblock menu_active_inspections %}	
{% block menu_inspections %}
<ul class="sub-menu active">
    <li class="active"><a href="{% url 'assignments:inspection_list'%}">{% blocktrans %}Make an Inspection{% endblocktrans %}</a></li>
</ul>
{% endblock menu_inspections %}
{% block content %}       
        {% include 'table_base.html' with info=dataTable %}        
<div class="modal fade" id="modal-dialog-custom">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <h4 class="modal-title">{% blocktrans %}Please select an employee{% endblocktrans %}</h4>
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
            </div>
            <div class="modal-body">
                <form method="post" class="form-horizontal">
                    {% csrf_token %}
                    <fieldset>
                        <div class="form-group">
                            {{form.employee|as_crispy_field }}
                        </div>		
                    </fieldset>
                </form>
                <div id="employ">
                </div>
            </div>
            <div class="modal-footer">
                <a href="javascript:;" class="btn btn-white" data-dismiss="modal">{% blocktrans %}Close{% endblocktrans %}</a>
                <a id="employee_red" href="javascript:;" class="btn btn-success">{% blocktrans %}Action{% endblocktrans %}</a>
            </div>
        </div>
    </div>
</div>
{% endblock content%}
{% block custom_js %}
	<link href="{% static 'plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" />
	<link href="{% static 'plugins/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" />
	<link href="{% static 'plugins/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" rel="stylesheet" />

    <script src="{% static 'custom_type.js' %}"></script>
	<!-- ================== BEGIN PAGE LEVEL JS ================== -->
		<!-- ================== BEGIN PAGE LEVEL JS ================== -->
	<script src="{% static 'plugins/datatables.net/js/jquery.dataTables.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>
	
	<script src="{% static 'plugins/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-buttons/js/buttons.print.min.js' %}"></script>

	<script src="{% static 'plugins/pdfmake/build/pdfmake.min.js' %}"></script>
	<script src="{% static 'plugins/pdfmake/build/vfs_fonts.js' %}"></script>
	<script src="{% static 'plugins/jszip/dist/jszip.min.js' %}"></script>
	<script src="{% static 'js/demo/table-manage-buttons.demo.js' %}"></script>
    <script src="{% static 'plugins/highlight.js/highlight.min.js' %}"></script>
    <script src="{% static 'js/demo/render.highlight.js' %}"></script>

<script>
    var token = '{{csrf_token}}';
    $('#id_employee').on('change', function() {
        var employee = this.value;
        var urlToAjax = "{% url 'assignments:delivered_ajax'%}";
        $.ajax({
            headers: { "X-CSRFToken": token },
            url: urlToAjax,
            type: 'GET',
            data: { 'id': employee },
            success: function(info) {
                var htmldata = "";
                if(info.response!="."){
                    if(info.gender==0){
                        var gender = 'Male';
                    }else{
                        var gender = 'Female';
                    }
                    htmldata += '\
                    <div class= row>\
                        <div class= "col-md-12 col-lg-4">\
                                <img class="img_profile" src="'+info.photo+'" >\
                        </div>\
                        <div class= "col-md-12 col-lg-8">\
                            <h4 class="widget-list-title m-b-6"><b>Name: </b><span class="text-capitalize">'+info.firts_name+' '+info.last_name+'</span></h4>\
                            <p class="widget-list-desc m-b-4"><b>Gender: </b>'+gender+'</p>\
                            <p class="widget-list-desc m-b-4"><b>Position: </b>'+info.position+'</p>\
                        </div>\
                    </div>' 
                }
                else{
                    htmldata +=" ";
                }
                var url=document.getElementById("employee_red");
                url.setAttribute("href","{% url 'assignments:inspection_select'%}?employee="+info.id) 
                $('#employ').html(htmldata);
            }
        });
    });
</script>
{% endblock custom_js %}

apps/assignments/templates/view_inspection.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="javascript:;">{% blocktrans %}Home{% endblocktrans %}</a></li>
    <li class="breadcrumb-item"><a href="javascript:;">{% blocktrans %}Inspection{% endblocktrans %}</a></li>
    <li class="breadcrumb-item active">{% blocktrans %}Make an Inspection{% endblocktrans %}</li>
{% endblock breadcrumb %}
{% block custom_css %}
	<link href="{% static '/css/stars.css' %}" rel="stylesheet" />
{% endblock custom_css %}
{% block page_header_title %}{% blocktrans %}Inspection{% endblocktrans %}{% endblock page_header_title %}
{% block page_header_sm_title %}{% blocktrans %}Here you can view the inpectioned elements{% endblocktrans %}{% endblock page_header_sm_title %}
{% block menu_active_inspections %}<li class="has-sub active">{% endblock menu_active_inspections %}	
{% block menu_inspections %}
<ul class="sub-menu active">
    <li class="active"><a href="{% url 'assignments:inspection_list'%}">{% blocktrans %}Make an Inspection{% endblocktrans %}</a></li>
</ul>
{% endblock menu_inspections %}
{% block content %}

{% include 'profile_base.html' with info=employee %} 


<div class="row">
    <div class="col-xl-12">
        <!-- begin panel -->
        <div class="panel panel-success">
            <!-- begin panel-heading -->
            <div class="panel-heading">
                <h4 class="panel-title"> {% blocktrans %}Inspection Results{% endblocktrans %} </h4>                
            </div>
            <!-- end panel-heading -->

			<div class="panel-body">
                <div class="row">

					<div class="col-xl-4 col-md-6">
						<div class="widget widget-stats bg-teal">
							<div class="stats-icon stats-icon-lg"><i class="fa fa-search fa-fw"></i></div>
							<div class="stats-content">
								<div class="stats-title">{% blocktrans %}Inspection result{% endblocktrans %}</div>
								<div class="stats-number">{{employee_inspect.qualification}}%</div>
								<div class="stats-progress progress">
									<div class="progress-bar" style="width: {{employee_inspect.qualification}}%;"></div>
								</div>
								<div class="stats-desc">{% blocktrans %}Approved Check List{% endblocktrans %} ({{employee_inspect.qualification}}%)</div>
							</div>
						</div>
					</div>
					
					<div class="col-xl-8 col-md-6">
						<div class="widget-chat widget-chat-rounded m-b-30" data-id="widget">		
							<div class="widget-chat-header">
								<div class="widget-chat-header-icon">
									<i class="fa fa-comment-alt  width-30 height-30 f-s-20 bg-yellow text-inverse text-center rounded-corner" style="line-height: 30px"></i>
								</div>
								<div class="widget-chat-header-content">
									<h4 class="widget-chat-header-title">{% blocktrans %}General Observations{% endblocktrans %}</h4>
									<p class="widget-chat-header-desc">{{employee_inspect.inspection_date | date}}</p>
								</div>
							</div>					
							<div class="widget-chat-body bg-grey-transparent-1" data-scrollbar="true" data-height="140px">
								<div class="widget-chat-item with-media left">
									<div class="widget-chat-media">
										<img alt="" src="{% static '/img/user/user-13.jpg' %}" />
									</div>
									<div class="widget-chat-info">
										<div class="widget-chat-info-container">
											<div class="widget-chat-name text-indigo">Hudson Mendes</div>
											<div class="widget-chat-message">{% lorem how_many_paragraphs %}</div>
											<div class="widget-chat-time">6:00PM</div>
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>				


				</div>
			</div>	

		</div>
	</div>
</div>			


{% for detail in delivery_details %}
<div class="row">
    <div class="col-xl-12">
        <!-- begin panel -->
        <div class="panel panel-success">
            <!-- begin panel-heading -->
            <div class="panel-heading"> 
                <h4 class="panel-title widget-list-title"> <span class="badge badge-info">{{ detail.supply.equipment.code }}</span> <b>{{ detail.supply.equipment.name|title }}</b></h4>                
            </div>
            <!-- end panel-heading -->
            
            <!-- begin panel-body -->
            <div class="panel-body">
                                
                <div class="row">
                    <!-- begin widget-list -->
                    <div class="widget-list widget-list-rounded m-b-30 col-lg-12" data-id="widget"> 
						<div class='row'>
							<table class='table table-striped table-bordered table-td-valign-middle '>
								<tr class="text-center f-s-15 ">
									<th >
										{% blocktrans %}Equipment{% endblocktrans %}
									</th>
									<th>
										{% blocktrans %}Details{% endblocktrans %}
									</th>
									<th>
										{% blocktrans %}Delivered Date{% endblocktrans %}
									</th>
									<th>
										{% blocktrans %}Result{% endblocktrans %}
									</th>									
								</tr>

								 <tr>
									<td width='30%' >
										<div class="media media-xs ">
											<a class="text-center block-center" href="javascript:;" >
												<img src="{{ detail.supply.equipment.image.url}}" alt="" 
													class="media-object rounded width-80 height-80" />
											</a>
											<div class="media-body">
												<p class='m-b-0 '>
													<strong class='f-s-14'>{{detail.supply.equipment_name |title  }}</strong>
												</p>
												<span >
													<small  class='f-s-11'>{{detail.supply.equipment_description|truncatechars:200 }}</small>
												</span>										
											</div>
										</div>    
									</td>
									<td>
																									
										<p class='m-b-0 '>
											<i class="fas fa-tags"></i>
											<span class="f-s-12"> <span>{% blocktrans %}Brand:{% endblocktrans %}</span> </span>
											<strong class='f-s-12'>{{detail.supply.brand |title }}</strong>
										</p>	
										<p class='m-b-0 '>
											<i class="fas fa-tshirt"></i>
											<span class="f-s-12"> <span>{% blocktrans %}Material:{% endblocktrans %}</span> </span>
											<strong class='f-s-12'>{{detail.supply.material |title }} {% blocktrans %}months{% endblocktrans %}</strong>
										</p>
										<p class='m-b-0 '>
											<i class="fas fa-ruler-combined"></i>
											<span class="f-s-12"> <span>{% blocktrans %}Size:{% endblocktrans %}</span> </span>
											<strong class='f-s-12'>{{detail.supply.size |title  }}</strong>
										</p>
										<p class='m-b-0 '>
											<i class="fas fa-palette"></i>
											<span class="f-s-12"> <span>{% blocktrans %}Color:{% endblocktrans %}</span> </span>
											<strong class='f-s-12'>{{detail.supply.color.name |title}}</strong>
										</p>
									</td>
									<td>
										<p class='m-b-0 '>
											<i class="fas fa-calendar-check"></i>
											<span class="f-s-12"> <span>{% blocktrans %}Delivered:{% endblocktrans %}</span> </span>
											<strong class='f-s-12'>{{detail.create_date|date:"M d, Y" }}</strong>
										</p>	
										<p class='m-b-0 '>
											<i class="fas fa-hourglass-start"></i>
											<span class="f-s-12"> <span>{% blocktrans %}Frequency of change:{% endblocktrans %}</span> </span>
											<strong class='f-s-12'>{{detail.supply.equipment.frequency_of_change_text }} </strong>
										</p>
										<p class='m-b-0 '>
											<i class="fas fa-calendar-times"></i>
											<span class="f-s-12"> <span>{% blocktrans %}Expire Date:{% endblocktrans %}</span> </span>
											<strong class='f-s-12'>{{detail.expire_date|date:"M d, Y" }}</strong>
										</p>
										<p class='m-b-0 '>
											<i class="fas fa-user-clock"></i>
											<span class="f-s-12"> <span>{% blocktrans %}Usage:{% endblocktrans %}</span> </span>
											<strong class='f-s-12'> 12 %</strong>			
											<span><div class="progress progress-sm rounded-corner m-b-0 width-150">
												<div class="progress-bar progress-bar-striped progress-bar-animated bg-green f-s-10 f-w-30 m-t-0 m-b-0" style="width: 24%;">12%</div>
											</div></span>
										</p>
										
									</td> 
									<td class="text-center">
										<span class="badge {{ detail.get_class_badge_level_average }} f-s-16">{{ detail.average}} %</span>
									</td>                                                                                                
								</tr>

							</table>
						</div>                      

							
							<div class='row bg-grey-transparent-1'>
								<div class='col-md-6'>
									<h4 class="widget-list-title"> <b>{% blocktrans %}Checklist for Inspections{% endblocktrans %}</b></h4>
									<table id="data-table-buttons" class="table table-striped table-bordered table-td-valign-middle">
										<thead>
											<tr> 
												<th class="text-nowrap">#</th>
												<th class="text-nowrap">{% blocktrans %}Checklist{% endblocktrans %}</th>
												<th class="text-nowrap text-center">{% blocktrans %}Approved{% endblocktrans %}</th>
												<th class="text-nowrap text-center">{% blocktrans %}Corrective Action{% endblocktrans %}</th>								 
											</tr>
										</thead>
										<tbody>
										{% for item in detail.employeeinspectiondetailresponse_set.all  %}
											<tr >
												<td>{{ forloop.counter }}</td>
												<td><b>{{item.items_inspection.check}}</b></td>
												<td class='text-center'>
												{% if  item.is_positive   %}
													<i class="fas fa-check text-teal fa-2x" aria-hidden="true"></i>
												{% else  %}
													<i class="fa fa-window-close text-red fa-2x" aria-hidden="true"></i>
												{% endif  %}
													
												</td>
												<td class='text-left'>
												{% if  item.is_positive   %}
													Ok
												{% else  %}
													{{item.items_inspection.corrective_action}}
												{% endif  %}
													
												</td>
											<tr>
										{% endfor  %}
										</tbody>
									</table >
								</div>
								<div class="col-md-6 ">
									<h4 class="widget-list-title"><b>{% blocktrans %}Comments:{% endblocktrans %} </b></h4>
									
									<div class="widget-chat widget-chat-rounded m-b-30" data-id="widget">		
															
										<div class="widget-chat-body bg-grey-transparent-1" data-scrollbar="true" data-height="140px">
											<div class="widget-chat-item with-media left">
												<div class="widget-chat-media">
													<img alt="" src="{% static '/img/user/user-13.jpg' %}" />
												</div>
												<div class="widget-chat-info">
													<div class="widget-chat-info-container">
														<div class="widget-chat-name text-indigo">Hudson Mendes</div>
														<div class="widget-chat-message">{% lorem how_many_paragraphs %}</div>
														<div class="widget-chat-time">{{employee_inspect.inspection_date | date}} 6:00PM</div>
													</div>
												</div>
											</div>
											<div class="widget-chat-item with-media left">
												<div class="widget-chat-media">
													<img alt="" src="{% static '/img/user/user-13.jpg' %}" />
												</div>
												<div class="widget-chat-info">
													<div class="widget-chat-info-container">
														<div class="widget-chat-name text-indigo">Hudson Mendes</div>
														<div class="widget-chat-message">{% lorem how_many_paragraphs %}</div>
														<div class="widget-chat-time">{{employee_inspect.inspection_date | date}} 6:00PM</div>
													</div>
												</div>
											</div>
										</div>
										
									</div>


								</div>
							</div>
							<br>
                    </div>
                </div>
            </div> 
            <!-- end panel-body -->
        </div>
        <!-- end panel -->
    </div>
</div>
{% endfor %}


	

{% endblock content%}