apps/elements/urls.py
from django.conf.urls import url
from django.urls import path,include
from . import views

from .views import TypeCreate, TypeList, TypeUpdate, TypeDelete, ClassificationCreate, ClassificationList, ClassificationUpdate,\
					ClassificationDelete,select_options_class_for_type

app_name = 'elements'
urlpatterns = [
	path('configurations/type/create', TypeCreate.as_view(), name='type_create'),
	path('configurations/type/list', TypeList.as_view(), name='type_list'),
	path('configurations/type/update/<int:pk>/', TypeUpdate.as_view(), name='type_update'),
	path('type_delete', TypeDelete.as_view(), name='type_delete'),
	path('configurations/classification/create', ClassificationCreate.as_view(), name='classification_create'),
	path('configurations/classification/list', ClassificationList.as_view(), name='classification_list'),
 	path('configurations/classification/update/<int:pk>/', ClassificationUpdate.as_view(), name='classification_update'),
 	path('classification_delete', ClassificationDelete.as_view(), name='classification_delete'),
	path('ajax/select_options_class_for_type', views.select_options_class_for_type, name='select_options_class_for_type'),
]

apps/requests/urls.py
from django.conf.urls import url
from django.urls import path,include
from django.views.generic import TemplateView
from django.conf import settings
from django.conf.urls.static import static

from .views import *

app_name = 'requests'
urlpatterns = [
	path('configurations/type/create', RequestTypeCreate.as_view(), name='request_type_create'),
	path('configurations/type/list', RequestTypeList.as_view(), name='request_type_list'),
	path('configurations/type/update/<int:pk>/', RequestTypeUpdate.as_view(), name='request_type_update'),
	path('type_delete', RequestsTypeDelete.as_view(), name='request_type_delete'),
	path('supplies-request', EmployeeRequestList.as_view(), name='supplies_request'),
	path('supplies-request/create/<int:pk>/', EmployeeRequestCreate.as_view(), name='supplies_request_create'),
	path('supplies-request/create/<int:pk>/details', EmployeeRequesDetailsCreate.as_view(), name='employee_request_detail_create'),
	path('supplies-request/create/<int:pk>/sender', EmployeeRequesSenderApproval.as_view(), name='employee_request_sender_approval'),
	path('supplies_request_delete/', EmployeeRequestDelete.as_view(), name='employee_request_delete'),
	path('supplies-request/create/details/edit/<int:pk>', EmployeeRequesDetailsUpdate.as_view(), name='employee_request_detail_edit'),
	path('supplies_request_create/details/delete', EmployeeRequesDetailsDelete.as_view(), name='employee_request_detail_delete'),
	path('supplies-request/create/<int:pk>/details/list', EmployeeRequesDetailsList.as_view(), name='employee_request_detail_list'),
	path('manage/list', ManageRequestList.as_view(), name='manage_request_list'),
	path('manage/show/<int:pk>', ManageRequesShow.as_view(), name='manage_request_show'),
	path('manage/approval/<int:pk>/<int:pks>', ManageRequesApproval.as_view(), name='manage_request_approval'),
	path('delivered_items', TemplateView.as_view(template_name='delivered_items.html'), name='delivered_items'),
	path('my_delivered', TemplateView.as_view(template_name='my_delivered.html'), name='my_delivered')
]

ippe/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
import notifications.urls
from django.contrib.staticfiles import views
from django.urls import re_path
from django.views.i18n import JavaScriptCatalog
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.base.urls', namespace='base')),
    path('login/', include('apps.authenticate.urls')),
    path('elements/', include('apps.elements.urls', namespace='elements')),
    path('sizes/', include('apps.sizes.urls', namespace='sizes')),
    path('requests/', include('apps.requests.urls', namespace='requests')),
    path('equipments/', include('apps.equipments.urls', namespace='equipments')),
    path('warehouses/', include('apps.warehouses.urls', namespace='warehouses')),
    #path('providers/', include('apps.inventories.urls', namespace='inventories')),
    path('employees/', include('apps.employees.urls', namespace='employees')),
    path('inventories/', include('apps.inventories.urls', namespace='inventories')),
    path('assignments/', include('apps.assignments.urls', namespace='assignments')),
    path('reports/', include('apps.reports.urls', namespace='reports')),
    path('publications/', include('apps.publications.urls', namespace='publications')),
    path('summernote/', include('django_summernote.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),

    path('api/v1/', include('apps.api.urls')),

    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('i18n/', include('django.conf.urls.i18n')),
]


if settings.DEBUG:
    
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', views.serve),
    ]
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/requests/models.py
from django.db import models

from apps.elements.models import Element_Type,Classification
from apps.employees.models import Employee,AssignedSize
from apps.organizational.models import Position,CostCenter,Location
from apps.equipments.models import Equipment, Color
from datetime import datetime
from django.db.models import Avg, Max, Min, Sum
from django.utils.translation import ugettext_lazy as _
# Create your models here.
class RequestType(models.Model):
    code = models.CharField(unique=True, max_length=10)
    name = models.CharField(max_length=50)
    detail = models.TextField(max_length=500)
    status = models.BooleanField(default=False)
    element_type = models.ForeignKey(Element_Type, null=True, blank=True, on_delete=models.SET_NULL)
    element_classification = models.ManyToManyField(Classification, blank=True, related_name='element_class')
    create_date = models.DateTimeField(auto_now_add=True)    
    modified_date = models.DateTimeField( auto_now=True)
    
    def __str__(self):
        return '(%s) %s ' % ( self.code, self.name)

    def status_text(self):
        return {True: 'Activated',False: 'Deactivated'}[self.status]        


# #   Solicitudes de suministros . emcabezado de solicitud antes SuppliesRequest
class EmployeeRequest(models.Model):
    CODE_CREATED = 0
    CODE_APPROVED = 1
    CODE_CANCELED = 2
    CODE_APPROVAL_FLOW = 3
    CODE_DELAYED = 4
    CODE_DECLINED = 5
    CODE_DISPACHED_COMPLETED = 6
    CODE_DISPACHED_INCOMPLETED = 7
    CODE_DELIVERY_RECEIVED = 8
    CODE_APPROVAL_COMPLETED = 9

    STATUS_CHOICES = [
        (CODE_CREATED, _('Created')),
        (CODE_APPROVED, _('Approved')),
        (CODE_CANCELED, _('Canceled')),
        (CODE_APPROVAL_FLOW, _('In Approbal Flow')),
        (CODE_DELAYED, _('Delayed')),
        (CODE_DECLINED, _('Declined')),
        (CODE_DISPACHED_COMPLETED, _('Dispached')),
        (CODE_DISPACHED_INCOMPLETED, _('Incompleted')),
        (CODE_DELIVERY_RECEIVED, _('Received')),
        (CODE_APPROVAL_COMPLETED, _('Approval completed!')),
        ]
    BADGE_CHOICES = [
        (CODE_CREATED,_('badge-warning')),
        (CODE_APPROVED, _('badge-success')),
        (CODE_CANCELED, _('badge-danger')),
        (CODE_APPROVAL_FLOW,_('badge-info')),
        (CODE_DELAYED, _('badge-warning')),
        (CODE_DECLINED, _('badge-danger')),
        (CODE_DISPACHED_COMPLETED, _('badge-success')),
        (CODE_DISPACHED_INCOMPLETED, _('badge-warning')),
        (CODE_DELIVERY_RECEIVED, _('badge-info')),
        (CODE_APPROVAL_COMPLETED, _('badge-success')),
        ]    

    employee = models.ForeignKey(Employee, null=True, blank=True, on_delete=models.SET_NULL)
    request_type = models.ForeignKey(RequestType, null=True, blank=True, on_delete=models.SET_NULL)
    position = models.ForeignKey(Position, null=True, blank=True, on_delete=models.SET_NULL)
    cost_center = models.ForeignKey(CostCenter, null=True, blank=True, on_delete=models.SET_NULL)
    location = models.ForeignKey(Location, null=True, blank=True, on_delete=models.SET_NULL)
    code = models.CharField(unique=True, max_length=30)
    observation = models.TextField(max_length=50)
    request_date = models.DateField()
    status_request = models.IntegerField(choices=STATUS_CHOICES, default=CODE_CREATED)
    next_level_approver = models.IntegerField(default=1)
    create_date = models.DateTimeField(auto_now_add=True)    
    modified_date = models.DateTimeField( auto_now=True)  

    def __str__(self):
        return '%s - %s ' % ( self.request_type, self.employee)

    def get_employee(self):
        return self.employee

    def request_status(self):
        return self.status_set.all()  

    def status_text(self):        
        return self.STATUS_CHOICES[self.status_request][1]    

    def get_level_badge(self):    
        return self.BADGE_CHOICES[self.status_request][1]

    def get_approver_request_list(self):
        approvers = WorkFlowApprovers.objects.filter( applicant = self.position , request_type=self.request_type ).all()    
        return approvers

    def get_status_list(self):    
        return self.status_set.order_by('-id')

    def get_last_status_activity(self):    
        return self.status_set.latest('id')    

    def get_approver_request(self):
        return WorkFlowApprovers.objects.get( applicant = self.position , request_type=self.request_type ,  level=self.next_level_approver)     

    def get_max_level_work_flow(self):
        level_max = WorkFlowApprovers.objects.filter( applicant = self.position , request_type=self.request_type ).aggregate(Max('level'))
        return level_max
class DetailRequest(models.Model):
    employee_request = models.ForeignKey(EmployeeRequest, null=True, blank=True, on_delete=models.SET_NULL)
    equipment = models.ForeignKey(Equipment, null=True, blank=True, on_delete=models.SET_NULL)
    assigned_size = models.ForeignKey(AssignedSize, null=True, blank=True, on_delete=models.SET_NULL)
    total = models.CharField(max_length=10)
    color = models.ForeignKey(Color,blank=True, null=True,on_delete=models.SET_NULL)
    create_date = models.DateTimeField(auto_now_add=True)    
    modified_date = models.DateTimeField( auto_now=True)

    def get_employee_request():
        return employee_request

class Status(models.Model):
    CODE_CREATED = 0
    CODE_APPROVED = 1
    CODE_CANCELED = 2
    CODE_APPROVAL_COMPLETED = 3
    CODE_DELAYED = 4
    CODE_DECLINED = 5
    CODE_DISPACHED_COMPLETED = 6
    CODE_DISPACHED_INCOMPLETED = 7
    CODE_RECEIVED_COMPLETED = 8
    CODE_SENDER_APPROVAL_FLOW = 9
    CODE_PENDING_DISPATCH = 10
    CODE_RECEIVED_INCOMPLETED = 11

    STATUS_CHOICES = [
        (CODE_CREATED, _('Created')),
        (CODE_APPROVED, _('Approved')),
        (CODE_CANCELED, _('Canceled')),
        (CODE_APPROVAL_COMPLETED, _('Full Approval')),
        (CODE_DELAYED, _('Delayed')),
        (CODE_DECLINED, _('Declined')),
        (CODE_DISPACHED_COMPLETED, _('Dispatched')),
        (CODE_DISPACHED_INCOMPLETED, _('Incompleted')),
        (CODE_RECEIVED_COMPLETED, _('Received Completed')),
        (CODE_SENDER_APPROVAL_FLOW, _('Sent to Approval')),
        (CODE_PENDING_DISPATCH, _('Pending dispatch')),
        (CODE_RECEIVED_INCOMPLETED, _('Received Incompleted')),
        ]

    BADGE_CHOICES = [
        (CODE_CREATED,_('warning')),
        (CODE_APPROVED, _('success')),
        (CODE_CANCELED, _('danger')),
        (CODE_APPROVAL_COMPLETED, _('success')),
        (CODE_DELAYED, _('warning')),
        (CODE_DECLINED, _('danger')),
        (CODE_DISPACHED_COMPLETED, _('success')),
        (CODE_DISPACHED_INCOMPLETED, _('warning')),
        (CODE_RECEIVED_COMPLETED, _('info')),
        (CODE_SENDER_APPROVAL_FLOW, _('info')),
        (CODE_PENDING_DISPATCH,  _('warning')),
        (CODE_RECEIVED_INCOMPLETED, _('warning')),
        ]     
        
    level = models.IntegerField(default=1)
    date =  models.DateField(default=datetime.now)
    observation = models.TextField(max_length=50)
    status = models.IntegerField(choices=STATUS_CHOICES, default=CODE_CREATED)
    employee_request = models.ForeignKey(EmployeeRequest, null=True, blank=True, on_delete=models.SET_NULL)
    employee = models.ForeignKey(Employee, null=True, blank=True, on_delete=models.SET_NULL)
    create_date = models.DateTimeField(auto_now_add=True)    
    modified_date = models.DateTimeField( auto_now=True)

    def __str__(self):
        return '(%s-%s) %s' % (self.level, self.STATUS_CHOICES[self.status][1], self.date)

    def status_text(self):        
        return self.STATUS_CHOICES[self.status][1]

    def status_class(self):        
        return self.BADGE_CHOICES[self.status][1]    

class WorkFlowApprovers(models.Model):
    request_type = models.ForeignKey(RequestType, null=True, blank=True, on_delete=models.SET_NULL)
    level = models.IntegerField(default=1)
    applicant = models.ForeignKey(Position,related_name='aplicant_position', null=True, blank=True, on_delete=models.SET_NULL)
    principal_approver = models.ForeignKey(Position,related_name='principal_approver_position', null=True, blank=True, on_delete=models.SET_NULL)
    auxiliar_approver = models.ForeignKey(Position,related_name='auxiliar_approver_position', null=True, blank=True, on_delete=models.SET_NULL)

    create_date = models.DateTimeField(auto_now_add=True)    
    modified_date = models.DateTimeField( auto_now=True)

    def __str__(self):
        return '(%s %s) %s %s' % (self.request_type.code, self.level,self.applicant.code, self.applicant.get_ocupate())

apps/requests/templates/request_detail_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load static %}
{% load i18n %}
{% block breadcrumb %}
	<li class="breadcrumb-item"><a href="javascript:;">{% blocktrans %}Home{% endblocktrans %}</a></li>
	<li class="breadcrumb-item"><a href="javascript:;">{% blocktrans %}Employee Request{% endblocktrans %}</a></li>
	<li class="breadcrumb-item active">{% blocktrans %}Registre{% endblocktrans %}</li>
{% endblock breadcrumb %}
{% block page_header_title %}{% blocktrans %}Request Employee - Detail{% endblocktrans %}{% endblock page_header_title %}
{% block page_header_sm_title %} {% blocktrans %}In this form you can create Request{% endblocktrans %}  {% endblock page_header_sm_title %}


{% block menu_active_sub_requests %}
	<li class="has-sub active">					
{% endblock menu_active_sub_requests %}
{% block menu_request %}
	<ul class="sub-menu active">
		<li class=" active"><a href="{% url 'requests:supplies_request'%}">{% blocktrans %}My Requests{% endblocktrans %}</a></li>
		<li><a href="{% url 'requests:manage_request_list' %}">{% blocktrans %}Manage Approval{% endblocktrans %}</a></li>
		<li><a href="{% url 'requests:my_delivered' %}">{% blocktrans %}My Delivered{% endblocktrans %} </a></li>
	</ul>						
{% endblock menu_request %}

{% block content %}

{% include 'profile_base.html' with info=employee %} 

			<div class="row">
				
				<!-- begin col-6 -->
				<div class="col-xl-12">
					<!-- begin panel -->
					<div class="panel panel-success" data-sortable-id="form-stuff-10">
						<!-- begin panel-heading -->
						<div class="panel-heading">
							<h4 class="panel-title">{% blocktrans %}Create - Details Request{% endblocktrans %} </h4>
							<div class="panel-heading-btn">
								<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
								<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
								<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
								<a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
							</div>
						</div>
						<!-- end panel-heading -->
						<!-- begin panel-body -->
						<div class="panel-body">

							<div class="row">
								<div class="col-md-2 col-md-offset-2">
									<label for="id_code" class="">
										<strong>{% blocktrans %}Code{% endblocktrans %}</strong>
									</label>     
									<div class="form-group">
										<span class="badge badge-success" >{{employee_request.code}}</span>
									</div>
								</div>
								<div class="col-md-4 col-md-offset-2 ">
									<div class="form-group">
										<div id="div_id_request_type" class="form-group">        
											<label for="id_request_type" class="">
												<strong>{% blocktrans %}Request Name{% endblocktrans %}</strong>
											</label>                                        
											<div class="form-group">
												<span class="badge badge-default" >{{employee_request.request_type.name}}</span>
											</div>
										</div>											
									</div>
								</div>
								<div class="col-md-6 col-md-offset-2 ">
									<div class="form-group">
									<div id="div_id_request_type" class="form-group">        
											<label for="id_request_type" class="">
												<strong>{% blocktrans %}Description{% endblocktrans %}</strong>
											</label>                                        
											<div class="form-group">
												<span  >{{employee_request.request_type.detail}}</span>
											</div>
										</div>
									</div>
								</div>										
							</div>
							<div class="row">
								<div class="col-md-2 col-md-offset-2">
									<label for="id_code" class="">
										<strong>{% blocktrans %}Date{% endblocktrans %}</strong>
									</label>     
									<div class="form-group">
										<span class="badge badge-success" >{{employee_request.request_date|date:"M d, Y"}}</span>
									</div>
								</div>
								<div class="col-md-4 col-md-offset-2 ">
									<div class="form-group">
										<div id="div_id_request_type" class="form-group">        
											<label for="id_request_type" class="">
												<strong>{% blocktrans %}Applicant Observation{% endblocktrans %}</strong>
											</label>                                        
											<div class="form-group">
												<span  class='f-s-10' >{{employee_request.observation}}</span>
											</div>
										</div>											
									</div>
								</div>	
								<div class="col-md-6 col-md-offset-2 ">
									<div class="form-group">
										<div id="div_id_request_type" class="form-group">        
											<label for="id_request_type" class="">
												<strong>{% blocktrans %}Approval Flow{% endblocktrans %}</strong>
											</label>                                        
											<div class="form-group">
												<li class="media media-xs">
														{% for approver in employee_request.get_approver_request_list %}										
															<a class="media-left" href="javascript:;">
																<img src="{{approver.principal_approver.get_ocupate.photo.url}}" alt=""
																title="{{approver.principal_approver.get_ocupate.get_short_name}}"
																	class="media-object rounded-corner height-40 width-40" />
															</a>															
														{% endfor %}
												</li>
											</div>
										</div>											
									</div>
								</div>															
							</div>
							<div class="row">
								<div class="col-md-12 col-md-offset-2 ">
									<hr width=100%>
									<h4 class='pull-left'>{% blocktrans %}Select of Equipment  to Request{% endblocktrans %}</h4>
									<p></p>							
								</div>								
							</div>

						
							<form method="post" class="form-horizontal">
                                {% csrf_token %}
								<fieldset>									
                                    <div class="row">										
																														
									</div>	
									<div class="row">
										<div class="col-md-4 col-md-offset-2">											    
                                        	<div class="form-group">
												<div id="div_id_equipment" class="form-group">        
													<label for="id_equipment" class="">
														{% blocktrans %}Equipment{% endblocktrans %} 
													</label>                                        
													<div class="">
													    <input name="employee_request" id="employee_request_id"  type="hidden" value="{{employee_request.id}}">
														<select name="equipment" class="form-control select select2-data form-control" id="id_equipment">														
														{% for option  in equipment_options  %}
															<optgroup label="{{ option.group.name }}">
																{% for op  in option.options  %}
																<option value="{{op.id}}"  >																	
																	<span>{{op.name|title }}</span>
																</option>
																{% endfor %}
															</optgroup>															
														{% endfor %}	
														</select>
													</div>
												</div>	
                                        	</div>
                                     	</div>
										<div class="col-md-2 col-md-offset-2 ">
											<div class="form-group">
												<label for="id_equipment_image" class="">
													{% blocktrans %}Image{% endblocktrans %} 
												</label> 
												<div class="media media-sm ">
													<a class="media center-block text-center" href="javascript:;" >
														<img src="../../../../../static/img/gallery/empty.jpg" id='image_equipment' alt="" class="media-object rounded height-100 width-100  center-block text-center" />
													</a>
												</div>  
											</div>
										</div>
										<div class="col-md-6 col-md-offset-2 ">
											<div class="form-group">
												<ul class="list-group">
													<li class="list-group-item"><span class='badge badge-lime '>{% blocktrans %}Code{% endblocktrans %}  </span>  <span id="equipment_code" ></span></li>
													<li class="list-group-item"><span class='badge badge-lime'>{% blocktrans %}Name{% endblocktrans %}  </span>   <span id="equipment_name" ></span></li>
													<li class="list-group-item"><span class='badge badge-lime'>{% blocktrans %}Desciption{% endblocktrans %} </span>  <span id="equipment_description" ></span></li>
													
												</ul>
											</div>
										</div>
										
									</div>		
									<div class="row">
										
										<div class="col-md-4 col-md-offset-2 ">
											<div class="form-group">
											{{form.assigned_size | as_crispy_field }}
											</div>
										</div>
										<div class="col-md-2 col-md-offset-2 ">
											<div class="form-group">
											{{form.total | as_crispy_field }}
											</div>
										</div>
										<div class="col-md-2 col-md-offset-2 ">
											<div class="form-group">
												{{form.color | as_crispy_field }}	
											</div>
										</div>	 
									</div>

                                     <div class="pull-right">								
                                      <button type="submit" class="btn btn-sm btn-primary m-r-5 ">{% blocktrans %}Add{% endblocktrans %}</button>
                                      <a class="btn btn-sm btn-secondary m-r-5  " href="{%url 'requests:supplies_request'  %}">{% blocktrans %}Back{% endblocktrans %}</a>
                                </div>
								</fieldset>
							</form>
						</div>
						<!-- end panel-body -->
						
					</div>
					<!-- end panel -->
				</div>
				
			</div>
			<!-- end row -->
    
	{% include 'table_base.html' with info=dataTable %}

	<div class="center-block text-center">
			<a class="btn btn-sm btn-primary m-r-5  text-center" href="{%url 'requests:employee_request_sender_approval' employee_request.id %}">{% blocktrans %}Sender Request{% endblocktrans %}</a>
	</div>
    
{% endblock %}


{% block custom_js %}
	<link href="{% static 'plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" />
	<link href="{% static 'plugins/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" />
	<link href="{% static 'plugins/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" rel="stylesheet" />

    <script src="{% static 'custom_type.js' %}"></script>
	<script src="{% static 'js/ajax_equipment.js' %}"></script>
	<!-- ================== BEGIN PAGE LEVEL JS ================== -->
		<!-- ================== BEGIN PAGE LEVEL JS ================== -->
	<script src="{% static 'plugins/datatables.net/js/jquery.dataTables.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>
	
	<script src="{% static 'plugins/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
	<script src="{% static 'plugins/datatables.net-buttons/js/buttons.print.min.js' %}"></script>

	<script src="{% static 'plugins/pdfmake/build/pdfmake.min.js' %}"></script>
	<script src="{% static 'plugins/pdfmake/build/vfs_fonts.js' %}"></script>
	<script src="{% static 'plugins/jszip/dist/jszip.min.js' %}"></script>
	<script src="{% static 'js/demo/table-manage-buttons.demo.js' %}"></script>
    <script src="{% static 'plugins/highlight.js/highlight.min.js' %}"></script>
    <script src="{% static 'js/demo/render.highlight.js' %}"></script>
	<!-- ================== END PAGE LEVEL JS ================== -->
	<!-- ================== END PAGE LEVEL JS ================== -->
	<!-- ================== END PAGE LEVEL JS ================== -->
	<!-- ================== END PAGE LEVEL JS ================== -->

	<link href="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/css/select2.min.css" rel="stylesheet" />
	<script src="https://cdn.jsdelivr.net/npm/select2@4.0.12/dist/js/select2.min.js"></script>  
	<script>$(".select2-data").select2({tags: true});</script>
{% endblock custom_js %}