apps/base/urls.py
from django.conf.urls import url
from django.urls import  include, path
from django.views.generic import TemplateView
from .views import indexViews, NotificationsView,Dashboard
from django.conf import settings
from django.conf.urls.static import static

app_name = 'base'

urlpatterns = [
    # path('', indexViews.as_view(), name='index'),
    path('', Dashboard.as_view(), name='index'),
    path('notifications/view/<int:pk>', NotificationsView.as_view(), name='notification_view'),
    # path('dashboard', Dashboard.as_view(), name='dashboard' ),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/reports/urls.py
from django.urls import path 
from django.urls import  include
from django.views.generic import TemplateView
from .views import ListHistoricalRecibed,ListHistoricalRequest,ListStorageinventory,ReportMatrizPPEforBusinessUnit,ReporFrequencyOfChangeEPP,NotificationList

app_name='reports' 

urlpatterns=[ 
    # path('Historic/', TemplateView.as_view(template_name="report1.html"),name="Historic"),
    path('report/recibed',ListHistoricalRecibed.as_view(),name="Historic_recibed"),
    path('report/request',ListHistoricalRequest.as_view(),name="Historic_request"),
    path('report/inventory',ListStorageinventory.as_view(),name="Historic_inventory"),
    path('report/matriz/EPP/business_units',ReportMatrizPPEforBusinessUnit.as_view(),name="report_matriz_ppe"),
    path('report/frequency_of_change/EPP/division',ReporFrequencyOfChangeEPP.as_view(),name="report_frequency_change_epp"),
    path('notification/list',NotificationList.as_view(),name="notification_list"),

]

ippe/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
import notifications.urls
from django.contrib.staticfiles import views
from django.urls import re_path
from django.views.i18n import JavaScriptCatalog
from django.conf.urls.i18n import i18n_patterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.base.urls', namespace='base')),
    path('login/', include('apps.authenticate.urls')),
    path('elements/', include('apps.elements.urls', namespace='elements')),
    path('sizes/', include('apps.sizes.urls', namespace='sizes')),
    path('requests/', include('apps.requests.urls', namespace='requests')),
    path('equipments/', include('apps.equipments.urls', namespace='equipments')),
    path('warehouses/', include('apps.warehouses.urls', namespace='warehouses')),
    #path('providers/', include('apps.inventories.urls', namespace='inventories')),
    path('employees/', include('apps.employees.urls', namespace='employees')),
    path('inventories/', include('apps.inventories.urls', namespace='inventories')),
    path('assignments/', include('apps.assignments.urls', namespace='assignments')),
    path('reports/', include('apps.reports.urls', namespace='reports')),
    path('publications/', include('apps.publications.urls', namespace='publications')),
    path('summernote/', include('django_summernote.urls')),
    path('inbox/notifications/', include(notifications.urls, namespace='notifications')),

    path('api/v1/', include('apps.api.urls')),

    path('jsi18n/', JavaScriptCatalog.as_view(), name='javascript-catalog'),
    path('i18n/', include('django.conf.urls.i18n')),
]


if settings.DEBUG:
    
    #urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += [
        re_path(r'^static/(?P<path>.*)$', views.serve),
    ]
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/reports/models.py
from django.db import models

# Create your models here.

apps/reports/views.py
from django.shortcuts import render
from django.views.generic import View, CreateView,UpdateView,DeleteView,ListView, DetailView
from ..assignments.models import *
from ..requests.models import *
from ..inventories.models import *
from ..organizational.models import *
from ..elements.models import *
from ..equipments.models import *
from django.urls import reverse_lazy
from django.contrib.auth.models import User
from notifications.models import Notification
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils.translation import ugettext_lazy as _

class ListHistoricalRecibed(LoginRequiredMixin,ListView):
    login_url ='authenticate:login'
    model = DeliveredDetail
    template_name = 'historical_recibed.html'

    def get_context_data(self, **kwargs):
        context = super(ListHistoricalRecibed, self).get_context_data(**kwargs)
        employee = self.request.user.employee
        deliv_ids = Delivered.objects.filter(employee = employee).values('id')
        # print(deliv_ids)
        supply_ids = DeliveredDetail.objects.filter(delivered_id__in = deliv_ids ).values('supply_id')
        delivery_details = DeliveredDetail.objects.filter(delivered_id__in = deliv_ids )

        data = delivery_details
        elements = []
        for d in data:
            elements.append([
                {
                    'type': 'image',
                    'content': d.supply.equipment.image.url
                },
                {
                    'type': 'code_name',
                    'content': {
                        'code':d.supply.code,
                        'name': d.supply.name
                    }
                },
                {
                    'type': 'label',
                    'content': [{'code':DeliveredDetail.STATUS_CHOICES[d.is_accept][1]}] 
                },
                {
                    'type': 'text',
                    'content': d.observation
                },
                {
                    'type': 'date',
                    'content': d.create_date
                },
                {
                    'type': 'text',
                    'content': d.expire_date
                },
                {
                    'type': 'employee_profile',
                    'content': d.delivered.deliverer.employee
                } 
            ])
        dataTable = {
            'card_tittle' : _('Items Delivery'),
            'headers': [_('Photo'), _('Supply'),_('Was accepted'),_('Observation'), _('Delivered Date'),_('Expire Date'), _('Delivered By')],
            'data': elements,
        }
        context['dataTable'] =  dataTable
        return context
class ListHistoricalRequest(LoginRequiredMixin,ListView):
    login_url ='authenticate:login'
    model = EmployeeRequest
    template_name = 'historical_request.html'
    
    def get_context_data(self, **kwargs):
        context = super(ListHistoricalRequest, self).get_context_data(**kwargs)
        employee = self.request.user.employee
        data = employee.employeerequest_set.all()
        elements = []
        for d in data:
            elements.append([
                {
                    'type': 'label',
                    'content': [{'code':d.code}]
                },
                {
                    'type': 'employee_profile',
                    'content': d.employee
                },
                {
                    'type': 'code_name',
                    'content':{
                        'code':d.request_type.code,
                        'name':d.request_type.name
                    }                     
                },
                {
                    'type': 'label',
                    'content': [{ 'code': 'Approved'}]  
                },
                # {
                #     'type': 'code_name',
                #     'content': {'code': d.cost_center.name,'name':d.cost_center}
                # },
                {
                    'type': 'text',
                    'content': d.location
                },
                
                {
                    'type': 'text',
                    'content': d.observation 
                },
                
                {
                    'type': 'date',
                    'content': d.create_date
                }, 
                
            ])
        dataTable = {
            'card_tittle' : _('My Request Made'),
            'headers': [_('Code'), _('Employee'), _('Request Type'), _('Status'), _('Location'), _('Observation'),_('Create Date')],
            'data': elements,
        }
        context['dataTable'] =  dataTable
        return context

class ListStorageinventory(LoginRequiredMixin,ListView):
    login_url ='authenticate:login'
    model = CheckinDetail
    template_name = 'historical_storage.html'

    def get_context_data(self, **kwargs):
        context = super(ListStorageinventory, self).get_context_data(**kwargs)
        data = CheckinDetail.objects.all()
        elements = []
        for d in data:
            a=d.supply.stocklevel_set.all().filter(warehouse=d.check_entry.warehouse.id)
            f=''
            if not a:
                f='not in stock'
            else:
                f=a.first().stock
            # print(f)
            elements.append([
                {
                    'type': 'name',
                    'content': d.check_entry.warehouse
                },
                {
                    'type': 'image',
                    'content': d.supply.equipment.image.url
                },
                {
                    'type': 'name',
                    'content': d.check_entry.provider
                },
                {
                    'type': 'label',
                    'content': [{'code': d.check_entry.bill}]
                },
                {
                    'type': 'code_name',
                    'content': {'code':d.check_entry.reason_movement.reason,'name': d.check_entry.reason_movement.movement_text()}
                },
                {
                    'type': 'name',
                    'content': d.check_entry.date_entry
                },
                {
                    'type': 'code_name',
                    'content':{'code':d.supply.size.code,'name':d.supply.size.name}
                },
                {
                    'type': 'name',
                    'content': d.supply.brand
                },
                {
                    'type': 'text',
                    'content': d.supply.material
                },
                {
                    'type': 'name',
                    'content': d.supply.color
                },
                {
                    'type': 'name',
                    'content': d.total 
                },
                {
                    'type': 'name',
                    'content': d.location
                }, 
                {
                    'type': 'name',
                    'content': d.expire_date
                }, 
                {
                     'type': 'name',
                    'content': f            
                }, 
            ])
        dataTable = {
            'card_tittle' : _('Storage Elements'),
            'headers': [_('Warehouse'), _('Supply'), _('Provider'), _('Invoice'), _('Reason'), _('Date'), _('Size'), _('Brand'),_('Material'),_('Color'),_('Total'),_('Location'),_('Expire Date'),_('Storage level')],
            'data': elements,
        }
        context['dataTable'] =  dataTable
        return context

class ReportMatrizPPEforBusinessUnit(LoginRequiredMixin,ListView):
    login_url ='authenticate:login'
    model = CheckinDetail
    template_name = 'report_matriz_ppe_for_bu.html'

    def get_context_data(self, **kwargs):
        context = super(ReportMatrizPPEforBusinessUnit, self).get_context_data(**kwargs)
       
        element_protection = Element_Type.objects.get(code='PPE')
        protection_class = element_protection.classification_set.all()
        businesUnit = BusinessUnit.objects.all()
        headers_complex = [] #Complex HEADER

        header_table =[ {
                    'name': _('Business Unit'),
                    'rowspan': "2",
                    'class':'text-center '
                },
               
                {
                    'name': _('Total Positions'),
                    'rowspan': "2",
                    'class':'text-center '
                }]

        for protection in protection_class:
            total = protection.equipment_set.count()
            if total > 0:
               header_table.append(
                    {
                    'name': protection.name,
                    'colspan': total,
                    'class':'text-center '
                    }
                   )
                
        headers_complex.append(header_table) 
        header_table = []        

        for protection in protection_class:
            for equipment in protection.equipment_set.filter(status=True):
                header_table.append(
                      {
                        'name': equipment.name,
                        'class':'text-center '
                      }
                     )

        headers_complex.append(header_table) 
        elements = []
        tr_body_data = []
        for d in businesUnit:
            postions = d.get_postions_structures()  
            tr_body_data.append(
                {
                    'type': 'name',
                    'content': d.name
                }
            )  
            tr_body_data.append( 
                {
                    'type': 'text',
                    'content': d.structure_count()
                }
            )  

            for protection in protection_class:
                for equipment in protection.equipment_set.filter(status=True):
                    total = 0
                    if postions:

apps/reports/templates/historical_recibed.html
3{% extends 'base.html' %}
{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}
{% block page_header_title %} {% blocktrans %}Items Delivery{% endblocktrans %}{% endblock page_header_title %}
{% block page_header_sm_title %} {% blocktrans %}Historical elements recibed{% endblocktrans %} {% endblock page_header_sm_title %}
{% block breadcrumb %}

<li class="breadcrumb-item"><a href="javascript:;">{% blocktrans %}Historical Elements recibed{% endblocktrans %}</a></li>

{% endblock breadcrumb %}
{% load static %}


{% block custom_css %}
<style>

</style>
{% endblock custom_css %}

{% block menu_active_Reports %}	
<li class="has-sub active">
{% endblock menu_active_Reports %}

{% block menu_Reports %}
<ul class="sub-menu active">
    <li class="active"><a href="{% url 'reports:Historic_recibed'%}">{% blocktrans %}Items Delivery{% endblocktrans %}</a></li>
    <li><a href="{% url 'reports:Historic_request'%}">{% blocktrans %}Requests Made{% endblocktrans %}</a></li>
    <li><a href="{% url 'reports:Historic_inventory'%}">{% blocktrans %}Storage inventory{% endblocktrans %}</a></li>
    <li ><a href="{% url 'reports:report_matriz_ppe'%}">{% blocktrans %}Matriz PPE for Business Unit{% endblocktrans %}</a></li>
    <li ><a href="{% url 'reports:report_frequency_change_epp'%}">{% blocktrans %}Frequency of Change EPP{% endblocktrans %}</a></li>
</ul> 
{% endblock menu_Reports %}	


{% block content %}
    {% include 'table_base.html' with info=dataTable %}
{% endblock %}


{% block custom_js %}

<link href="{% static 'plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" />
<link href="{% static 'plugins/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" />
<link href="{% static 'plugins/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" rel="stylesheet" />

<script src="{% static 'custom_type.js' %}"></script>
<!-- ================== BEGIN PAGE LEVEL JS ================== -->
    <!-- ================== BEGIN PAGE LEVEL JS ================== -->
<script src="{% static 'plugins/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>

<script src="{% static 'plugins/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons/js/buttons.print.min.js' %}"></script>

<script src="{% static 'plugins/pdfmake/build/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/build/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/jszip/dist/jszip.min.js' %}"></script>
<script src="{% static 'js/demo/table-manage-buttons.demo.js' %}"></script>
<script src="{% static 'plugins/highlight.js/highlight.min.js' %}"></script>
<script src="{% static 'js/demo/render.highlight.js' %}"></script>

{% endblock custom_js %}

apps/reports/templates/historical_request.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% load i18n %}
{% block page_header_title %} {% blocktrans %}Requests Made {% endblocktrans %}{% endblock page_header_title %}
{% block page_header_sm_title %}{% blocktrans %}Requests Made {% endblocktrans %} {% endblock page_header_sm_title %}
{% block breadcrumb %}


<li class="breadcrumb-item"><a href="javascript:;">{% blocktrans %}Requests Made{% endblocktrans %}</a></li>

{% endblock breadcrumb %}
{% load static %}


{% block custom_css %}
<style>

</style>
{% endblock custom_css %}

{% block menu_active_Reports %}	
<li class="has-sub active">
{% endblock menu_active_Reports %}

{% block menu_Reports %}
<ul class="sub-menu active">
<li ><a href="{% url 'reports:Historic_recibed'%}">{% blocktrans %}Items Delivery{% endblocktrans %}</a></li>
    <li class="active"><a href="{% url 'reports:Historic_request'%}">{% blocktrans %}Requests Made{% endblocktrans %}</a></li>
    <li><a href="{% url 'reports:Historic_inventory'%}">{% blocktrans %}Storage inventory{% endblocktrans %}</a></li>
    <li ><a href="{% url 'reports:report_matriz_ppe'%}">{% blocktrans %}Matriz PPE for Business Unit{% endblocktrans %}</a></li>
    <li ><a href="{% url 'reports:report_frequency_change_epp'%}">{% blocktrans %}Frequency of Change EPP{% endblocktrans %}</a></li>
</ul> 
{% endblock menu_Reports %}	


{% block content %}
    {% include 'table_base.html' with info=dataTable %}
{% endblock %}


{% block custom_js %}

<link href="{% static 'plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" />
<link href="{% static 'plugins/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" />
<link href="{% static 'plugins/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" rel="stylesheet" />

<script src="{% static 'custom_type.js' %}"></script>
<!-- ================== BEGIN PAGE LEVEL JS ================== -->
    <!-- ================== BEGIN PAGE LEVEL JS ================== -->
<script src="{% static 'plugins/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>

<script src="{% static 'plugins/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons/js/buttons.print.min.js' %}"></script>

<script src="{% static 'plugins/pdfmake/build/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/build/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/jszip/dist/jszip.min.js' %}"></script>
<script src="{% static 'js/demo/table-manage-buttons.demo.js' %}"></script>
<script src="{% static 'plugins/highlight.js/highlight.min.js' %}"></script>
<script src="{% static 'js/demo/render.highlight.js' %}"></script>

{% endblock custom_js %}

apps/reports/templates/historical_storage.html
{% extends 'base.html' %}
{% load static %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block page_header_title %} {% blocktrans %}Elements in storage{% endblocktrans %}  {% endblock page_header_title %}
{% block page_header_sm_title %} {% blocktrans %}Elements in storage{% endblocktrans %} {% endblock page_header_sm_title %}
{% block breadcrumb %}

<li class="breadcrumb-item"><a href="javascript:;">{% blocktrans %}Storage Elements{% endblocktrans %}</a></li>

{% endblock breadcrumb %}
{% load static %}


{% block custom_css %}
<style>

</style>
{% endblock custom_css %}

{% block menu_active_Reports %}	
<li class="has-sub active">
{% endblock menu_active_Reports %}

{% block menu_Reports %}
<ul class="sub-menu active">
    <li ><a href="{% url 'reports:Historic_recibed'%}">Items Delivery</a></li>
    <li><a href="{% url 'reports:Historic_request'%}">{% blocktrans %}Requests Made{% endblocktrans %}</a></li>
    <li  class="active"><a href="{% url 'reports:Historic_inventory'%}">{% blocktrans %}Storage inventory{% endblocktrans %}</a></li>
    <li ><a href="{% url 'reports:report_matriz_ppe'%}">{% blocktrans %}Matriz PPE for Business Unit{% endblocktrans %}</a></li>
    <li ><a href="{% url 'reports:report_frequency_change_epp'%}">{% blocktrans %}Frequency of Change EPP{% endblocktrans %}</a></li>
</ul> 
{% endblock menu_Reports %}	


{% block content %}
    {% include 'table_base.html' with info=dataTable %}
{% endblock %}


{% block custom_js %}

<link href="{% static 'plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" />
<link href="{% static 'plugins/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" />
<link href="{% static 'plugins/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" rel="stylesheet" />

<script src="{% static 'custom_type.js' %}"></script>
<!-- ================== BEGIN PAGE LEVEL JS ================== -->
    <!-- ================== BEGIN PAGE LEVEL JS ================== -->
<script src="{% static 'plugins/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>

<script src="{% static 'plugins/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons/js/buttons.print.min.js' %}"></script>

<script src="{% static 'plugins/pdfmake/build/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/build/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/jszip/dist/jszip.min.js' %}"></script>
<script src="{% static 'js/demo/table-manage-buttons.demo.js' %}"></script>
<script src="{% static 'plugins/highlight.js/highlight.min.js' %}"></script>
<script src="{% static 'js/demo/render.highlight.js' %}"></script>

{% endblock custom_js %}

apps/reports/templates/report_frequency_of_change_for_division.html
{% extends 'base.html' %}
{% load i18n %}
{% load crispy_forms_tags %}
{% block page_header_title %} {% blocktrans %}Frequency of change for Divisions {% endblocktrans %} {% endblock page_header_title %}
{% block page_header_sm_title %} {% blocktrans %}Frequency of change personal protection elements for  Divisions {% endblocktrans %} {% endblock page_header_sm_title %}


{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="javascript:;">{% blocktrans %}Home{% endblocktrans %}</a></li>
    <li class="breadcrumb-item"><a href="javascript:;">{% blocktrans %}Frequency of change for Divisions{% endblocktrans %}</a></li>
    <li class="breadcrumb-item active">{% blocktrans %}Data Table{% endblocktrans %}</li>
{% endblock breadcrumb %}

{% load static %}


{% block custom_css %}
<style>

</style>
{% endblock custom_css %}

{% block menu_active_Reports %}	
<li class="has-sub active">
{% endblock menu_active_Reports %}

{% block menu_Reports %}
<ul class="sub-menu active">
    <li ><a href="{% url 'reports:Historic_recibed'%}">{% blocktrans %}Items Delivery{% endblocktrans %}</a></li>
   <li ><a href="{% url 'reports:Historic_request'%}">{% blocktrans %}Requests Made{% endblocktrans %}</a></li>
    <li><a href="{% url 'reports:Historic_inventory'%}">{% blocktrans %}Storage inventory{% endblocktrans %}</a></li>
    <li ><a href="{% url 'reports:report_matriz_ppe'%}">{% blocktrans %}Matriz PPE for Business Unit{% endblocktrans %}</a></li>
    <li class="active"><a href="{% url 'reports:report_frequency_change_epp'%}">{% blocktrans %}Frequency of Change EPP{% endblocktrans %}</a></li>
</ul> 
{% endblock menu_Reports %}	


{% block content %}
    {% include 'table_base.html' with info=dataTable %}
{% endblock %}


{% block custom_js %}

<link href="{% static 'plugins/datatables.net-bs4/css/dataTables.bootstrap4.min.css' %}" rel="stylesheet" />
<link href="{% static 'plugins/datatables.net-responsive-bs4/css/responsive.bootstrap4.min.css' %}" rel="stylesheet" />
<link href="{% static 'plugins/datatables.net-buttons-bs4/css/buttons.bootstrap4.min.css' %}" rel="stylesheet" />

<script src="{% static 'custom_type.js' %}"></script>
<!-- ================== BEGIN PAGE LEVEL JS ================== -->
    <!-- ================== BEGIN PAGE LEVEL JS ================== -->
<script src="{% static 'plugins/datatables.net/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-bs4/js/dataTables.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-responsive/js/dataTables.responsive.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-responsive-bs4/js/responsive.bootstrap4.min.js' %}"></script>

<script src="{% static 'plugins/datatables.net-buttons/js/dataTables.buttons.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons-bs4/js/buttons.bootstrap4.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons/js/buttons.colVis.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons/js/buttons.flash.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons/js/buttons.html5.min.js' %}"></script>
<script src="{% static 'plugins/datatables.net-buttons/js/buttons.print.min.js' %}"></script>

<script src="{% static 'plugins/pdfmake/build/pdfmake.min.js' %}"></script>
<script src="{% static 'plugins/pdfmake/build/vfs_fonts.js' %}"></script>
<script src="{% static 'plugins/jszip/dist/jszip.min.js' %}"></script>
<script src="{% static 'js/demo/table-manage-buttons.demo.js' %}"></script>
<script src="{% static 'plugins/highlight.js/highlight.min.js' %}"></script>
<script src="{% static 'js/demo/render.highlight.js' %}"></script>

{% endblock custom_js %}